name: Transfuser
version: '1.0.0'
main: net.stardew.transfuser.Transfuser
api-version: '1.20'
commands:
  transfuser:
    description: Transfuser main command
    aliases: [transf]
    usage: /transfuser <create|destroy|get|give>
    permission: transfuser.use
permissions:
  transfuser.use:
    description: Allows a player to use transfuser commands
    default: true
  transfuser.admin:
    description: Allows a player to use admin commands for transfuser
    default: op