name: Transfuser
version: 1.0.1
main: net.stardew.transfuser.Transfuser
author: [Snycent]
api-version: 1.20
commands:
  transfuser:
    description: Transfuser main command
    aliases: [transf]
    usage: /transfuser <create|destroy|get|give>
    permission: transfuser.use
permissions:
  transfuser.use:
    description: Allows a player to use transfuser commands
    default: true
  transfuser.create:
    description: Allows a player to create a transfuser
    default: true
  transfuser.destroy:
    description: Allows a player to destroy a transfuser
    default: true
  transfuser.rename:
    description: Allows a player to rename a transfuser
    default: true
  transfuser.admin:
    description: Allows a player to use admin commands for transfuser
    default: op